# CQ16.2: What are the foreseeable unintended outcomes and sources of risks to health and safety, fundamental rights and discrimination?
# Requirement 16: Monitoring, functioning and control

PREFIX aidoc: <https://w3id.org/aidoc-ap#>
PREFIX airo: <https://w3id.org/airo#>
PREFIX vair: <https://w3id.org/vair#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?system ?systemLabel ?risk ?riskDescription ?riskSource ?consequence
WHERE {
  ?system a aidoc:AISystem .
  OPTIONAL { ?system rdfs:label ?systemLabel . }
  ?system aidoc:hasRisk ?risk .
  OPTIONAL { ?risk dcterms:description ?riskDescription . }
  OPTIONAL { ?riskSource airo:isRiskSourceFor ?risk . }
  OPTIONAL { ?risk airo:hasConsequence ?consequence . }
}
