# CQ5.1: What hardware does the AI system need to run?
# Requirement 5: Hardware required

PREFIX aidoc: <https://w3id.org/aidoc-ap#>
PREFIX server: <http://w3id.org/devops-infra/server#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?system ?systemLabel ?hardware ?hardwareType ?cpu ?memory ?numCPUs ?os
WHERE {
  ?system a aidoc:AISystem .
  OPTIONAL { ?system rdfs:label ?systemLabel . }
  ?system aidoc:requiresHardware ?hardware .
  OPTIONAL { ?hardware a ?hardwareType . FILTER(?hardwareType != owl:NamedIndividual) }
  OPTIONAL { ?hardware server:cpu ?cpu . }
  OPTIONAL { ?hardware server:memory ?memory . }
  OPTIONAL { ?hardware server:numberCPUs ?numCPUs . }
  OPTIONAL { ?hardware server:operatingSystem ?os . }
}
