name: coverage
services:
    coverage:
        image: ghcr.io/certain-project/aidoc-coverage:latest
        ports:
            - ${PORT:-3000}:3000
        environment:
            - SPARQL_ENDPOINT_URL=${SPARQL_ENDPOINT_URL?configure URL or set empty for examples}
        read_only: true
